name: Cypress Telnyx Testing

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./Telnyx
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: "https://telnyx.com/"
        env:
            GITHUB_TOKEN: ${{ secrets.TELNYXTESTS }}
          
          
    
